version: '3.5'
services:

#mysql manager 1
   mysql-manager-1:
     image: mysql/mysql-cluster:8.0
     container_name: management1
     networks:
      static_ip:
        ipv4_address: 198.168.0.2
     restart:      always
     volumes:
       - ./cnf/my.cnf:/etc/my.cnf
       - ./cnf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
     command: ndb_mgmd
 
#mysql manager 2
   mysql-manager-2:
     image: mysql/mysql-cluster:8.0
     container_name: management2
     networks:
      static_ip:
        ipv4_address: 198.168.0.3
     restart:      always
     volumes:
       - ./cnf/my.cnf:/etc/my.cnf
       - ./cnf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
     command: ndb_mgmd
       
#mysql Data Node 1
   data-node1:
     image: mysql/mysql-cluster:8.0
     container_name: ndb1
     networks:
      static_ip:
        ipv4_address: 198.168.0.4
     restart:      always
     volumes:
       - ./cnf/my.cnf:/etc/my.cnf
       - ./cnf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
     command: ndbd

#mysql Data Node 2
   data-node2:
     image: mysql/mysql-cluster:8.0
     container_name: ndb2
     networks:
      static_ip:
        ipv4_address: 198.168.0.5
     restart:      always
     volumes:
       - ./cnf/my.cnf:/etc/my.cnf
       - ./cnf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
     command: ndbd

#mysql-server-1
   mysql-server-1:
     image: mysql/mysql-cluster:8.0
     container_name: mysql1
     environment: 
       - "MYSQL_ROOT_PASSWORD=pucsd"
       - "MYSQL_USER=shubham"
       - "MYSQL_PASSWORD=shubham"
       - "MYSQL_DATABASE=shubham"
     networks:
      static_ip:
        ipv4_address: 198.168.0.9
     restart:      always
     volumes:
       - ./cnf/my.cnf:/etc/my.cnf
       - ./cnf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
       - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
     command:      mysqld
     ports:
       - 3307:3306

#mysql-server 2
   mysql-server-2:
     image: mysql/mysql-cluster:8.0
     container_name: mysql2
     environment: 
       - "MYSQL_ROOT_PASSWORD=pucsd"
       - "MYSQL_USER=shubham"
       - "MYSQL_PASSWORD=shubham"
       - "MYSQL_DATABASE=shubham"
     networks:
      static_ip:
        ipv4_address: 198.168.0.10
     restart:      always
     volumes:
       - ./cnf/my.cnf:/etc/my.cnf
       - ./cnf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
       - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
     command:      mysqld
     ports:
       - 3308:3306

# Networks to be created to facilitate communication between containers
networks:
  static_ip:
    name: my_network
    ipam:
      driver: default
      config:
        - subnet: 198.168.0.0/16
